FROM golang:1.13 AS builder

ENV TZ Asia/Shanghai

ARG VERSION
ENV RELEASE_VER ${VERSION}
WORKDIR ${GOPATH}/src/volcano.sh/volcano
COPY . .
RUN make vc-controller-manager

FROM debian:10

ENV TZ Asia/Shanghai

COPY --from=builder /go/src/volcano.sh/volcano/_output/bin/vc-controller-manager /vc-controller-manager
ENTRYPOINT ["/vc-controller-manager"]
