FROM golang:1.13 AS builder

ENV TZ Asia/Shanghai

ARG VERSION
ENV VERSION ${VERSION}
WORKDIR ${GOPATH}/src/volcano.sh/volcano
COPY . .
RUN make vc-scheduler

FROM debian:10

ENV TZ Asia/Shanghai

COPY --from=builder /go/src/volcano.sh/volcano/_output/bin/vc-scheduler /vc-scheduler
ENTRYPOINT ["/vc-scheduler"]
